/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package organillama.llamadevelopers;

import java.awt.Image;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Colque
 */
public class Login extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Arranque
     */
    public Login() {
        this.setUndecorated(true);
        
        initComponents();
        this.setLocationRelativeTo(null);

       // Shape forma = new RoundRectangle2D.Double(0,0,this.getBounds(),width,this.getBounds(),height,27,27);

        ImageIcon imagen = new ImageIcon("src\\main\\java\\organillama\\llamadevelopers\\Imagenes\\login.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(FondoLlamaDevelopers.getWidth(), FondoLlamaDevelopers.getHeight(), Image.SCALE_DEFAULT));
        FondoLlamaDevelopers.setIcon(icono);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UsuarioLbl = new javax.swing.JLabel();
        UsuarioTxt = new javax.swing.JTextField();
        ContraseñaLbl = new javax.swing.JLabel();
        ContraseñaTxt = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TituloTxt1 = new javax.swing.JLabel();
        TituloTxt2 = new javax.swing.JLabel();
        TituloTxt3 = new javax.swing.JLabel();
        CerrarBtn = new javax.swing.JPanel();
        CerrarLbl = new javax.swing.JLabel();
        MinimizarBtn = new javax.swing.JPanel();
        MinimizarLbl = new javax.swing.JLabel();
        FondoLlamaDevelopers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsuarioLbl.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        UsuarioLbl.setText("Usuario:");
        jPanel1.add(UsuarioLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));
        jPanel1.add(UsuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 240, 40));

        ContraseñaLbl.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        ContraseñaLbl.setText("Contraseña:");
        jPanel1.add(ContraseñaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        ContraseñaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaTxtActionPerformed(evt);
            }
        });
        jPanel1.add(ContraseñaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 240, 40));

        jButton1.setBackground(new java.awt.Color(255, 130, 0));
        jButton1.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 120, 40));

        jButton2.setBackground(new java.awt.Color(255, 130, 0));
        jButton2.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Registrate");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 130, 40));

        TituloTxt1.setFont(new java.awt.Font("Elephant", 0, 40)); // NOI18N
        TituloTxt1.setText("Bienvenido A");
        jPanel1.add(TituloTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 280, 50));

        TituloTxt2.setFont(new java.awt.Font("Elephant", 0, 40)); // NOI18N
        TituloTxt2.setText("Organi");
        jPanel1.add(TituloTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 60));

        TituloTxt3.setFont(new java.awt.Font("Elephant", 0, 44)); // NOI18N
        TituloTxt3.setForeground(new java.awt.Color(204, 102, 0));
        TituloTxt3.setText("Llama");
        jPanel1.add(TituloTxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        CerrarBtn.setBackground(new java.awt.Color(255, 51, 51));
        CerrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarBtnMouseClicked(evt);
            }
        });

        CerrarLbl.setText("X");

        javax.swing.GroupLayout CerrarBtnLayout = new javax.swing.GroupLayout(CerrarBtn);
        CerrarBtn.setLayout(CerrarBtnLayout);
        CerrarBtnLayout.setHorizontalGroup(
            CerrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CerrarBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CerrarLbl)
                .addGap(14, 14, 14))
        );
        CerrarBtnLayout.setVerticalGroup(
            CerrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CerrarBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CerrarLbl)
                .addGap(24, 24, 24))
        );

        jPanel1.add(CerrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 30));

        MinimizarBtn.setBackground(new java.awt.Color(51, 153, 0));
        MinimizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarBtnMouseClicked(evt);
            }
        });

        MinimizarLbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MinimizarLbl.setText("_");
        MinimizarLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        MinimizarLbl.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout MinimizarBtnLayout = new javax.swing.GroupLayout(MinimizarBtn);
        MinimizarBtn.setLayout(MinimizarBtnLayout);
        MinimizarBtnLayout.setHorizontalGroup(
            MinimizarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MinimizarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MinimizarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MinimizarBtnLayout.setVerticalGroup(
            MinimizarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MinimizarBtnLayout.createSequentialGroup()
                .addComponent(MinimizarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.add(MinimizarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 30));

        FondoLlamaDevelopers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FondoLlamaDevelopersMouseClicked(evt);
            }
        });
        jPanel1.add(FondoLlamaDevelopers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContraseñaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaTxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CerrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CerrarBtnMouseClicked

    private void MinimizarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarBtnMouseClicked
        setExtendedState(ICONIFIED);

    }//GEN-LAST:event_MinimizarBtnMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
//        x=evt.getX();
  //      x=evt.getY();
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void FondoLlamaDevelopersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoLlamaDevelopersMouseClicked
       // x=evt.getX();
       // x=evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_FondoLlamaDevelopersMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        inicio l = new inicio();
            l.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        registro l = new registro();
            l.setVisible(true);
            this.dispose();

    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CerrarBtn;
    private javax.swing.JLabel CerrarLbl;
    private javax.swing.JLabel ContraseñaLbl;
    private javax.swing.JPasswordField ContraseñaTxt;
    private javax.swing.JLabel FondoLlamaDevelopers;
    private javax.swing.JPanel MinimizarBtn;
    private javax.swing.JLabel MinimizarLbl;
    private javax.swing.JLabel TituloTxt1;
    private javax.swing.JLabel TituloTxt2;
    private javax.swing.JLabel TituloTxt3;
    private javax.swing.JLabel UsuarioLbl;
    private javax.swing.JTextField UsuarioTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
