/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package organillama.llamadevelopers;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Colque
 */
public class registro extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Arranque
     */
    public registro() {
        this.setUndecorated(true);
        
        initComponents();
        this.setLocationRelativeTo(null);

       // Shape forma = new RoundRectangle2D.Double(0,0,this.getBounds(),width,this.getBounds(),height,27,27);

        ImageIcon imagen = new ImageIcon("src\\main\\java\\organillama\\llamadevelopers\\Imagenes\\inicio.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(FondoLlamaDevelopers.getWidth(), FondoLlamaDevelopers.getHeight(), Image.SCALE_DEFAULT));
        FondoLlamaDevelopers.setIcon(icono);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloTxt1 = new javax.swing.JLabel();
        TituloTxt2 = new javax.swing.JLabel();
        TituloTxt3 = new javax.swing.JLabel();
        CerrarBtn = new javax.swing.JPanel();
        CerrarLbl = new javax.swing.JLabel();
        MinimizarBtn = new javax.swing.JPanel();
        MinimizarLbl = new javax.swing.JLabel();
        usuariolbl = new javax.swing.JLabel();
        passwordlbl = new javax.swing.JLabel();
        confirmarpasslbl = new javax.swing.JLabel();
        fechadenacimientolbl = new javax.swing.JLabel();
        registrarbtn = new javax.swing.JButton();
        cancelarbtn = new javax.swing.JButton();
        usuariotxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JPasswordField();
        confirmarpasstxt = new javax.swing.JPasswordField();
        fechadenaciminetotxt = new com.toedter.calendar.JDateChooser();
        FondoLlamaDevelopers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloTxt1.setFont(new java.awt.Font("Elephant", 0, 40)); // NOI18N
        TituloTxt1.setText("Registrate en");
        jPanel1.add(TituloTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 280, 50));

        TituloTxt2.setFont(new java.awt.Font("Elephant", 0, 40)); // NOI18N
        TituloTxt2.setText("Organi");
        jPanel1.add(TituloTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 180, 60));

        TituloTxt3.setFont(new java.awt.Font("Elephant", 0, 44)); // NOI18N
        TituloTxt3.setForeground(new java.awt.Color(204, 102, 0));
        TituloTxt3.setText("Llama");
        jPanel1.add(TituloTxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        CerrarBtn.setBackground(new java.awt.Color(255, 51, 51));
        CerrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarBtnMouseClicked(evt);
            }
        });

        CerrarLbl.setText("X");

        javax.swing.GroupLayout CerrarBtnLayout = new javax.swing.GroupLayout(CerrarBtn);
        CerrarBtn.setLayout(CerrarBtnLayout);
        CerrarBtnLayout.setHorizontalGroup(
            CerrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CerrarBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CerrarLbl)
                .addGap(14, 14, 14))
        );
        CerrarBtnLayout.setVerticalGroup(
            CerrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CerrarBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CerrarLbl)
                .addGap(24, 24, 24))
        );

        jPanel1.add(CerrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 30));

        MinimizarBtn.setBackground(new java.awt.Color(51, 153, 0));
        MinimizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarBtnMouseClicked(evt);
            }
        });

        MinimizarLbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MinimizarLbl.setText("_");
        MinimizarLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        MinimizarLbl.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout MinimizarBtnLayout = new javax.swing.GroupLayout(MinimizarBtn);
        MinimizarBtn.setLayout(MinimizarBtnLayout);
        MinimizarBtnLayout.setHorizontalGroup(
            MinimizarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MinimizarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MinimizarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MinimizarBtnLayout.setVerticalGroup(
            MinimizarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MinimizarBtnLayout.createSequentialGroup()
                .addComponent(MinimizarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.add(MinimizarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 30));

        usuariolbl.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        usuariolbl.setText("Usuario:");
        jPanel1.add(usuariolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 220, 30));

        passwordlbl.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        passwordlbl.setText("Contrasenia:");
        jPanel1.add(passwordlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 220, 30));

        confirmarpasslbl.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        confirmarpasslbl.setText("Confirmar Contrasenia:");
        jPanel1.add(confirmarpasslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 220, 30));

        fechadenacimientolbl.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        fechadenacimientolbl.setText("Fecha De Nacimiento:");
        jPanel1.add(fechadenacimientolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 220, 30));

        registrarbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        registrarbtn.setText("Registrar");
        jPanel1.add(registrarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 120, 30));

        cancelarbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        cancelarbtn.setText("Cancelar");
        cancelarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarbtnMouseClicked(evt);
            }
        });
        jPanel1.add(cancelarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 120, 30));

        usuariotxt.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        usuariotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariotxtActionPerformed(evt);
            }
        });
        jPanel1.add(usuariotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 220, 30));

        passwordtxt.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jPanel1.add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 220, 30));
        jPanel1.add(confirmarpasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 220, 30));
        jPanel1.add(fechadenaciminetotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 220, 30));

        FondoLlamaDevelopers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FondoLlamaDevelopersMouseClicked(evt);
            }
        });
        jPanel1.add(FondoLlamaDevelopers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CerrarBtnMouseClicked

    private void MinimizarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarBtnMouseClicked
        setExtendedState(ICONIFIED);

    }//GEN-LAST:event_MinimizarBtnMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
//        x=evt.getX();
  //      x=evt.getY();
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void FondoLlamaDevelopersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoLlamaDevelopersMouseClicked
       // x=evt.getX();
       // x=evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_FondoLlamaDevelopersMouseClicked

    private void usuariotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariotxtActionPerformed

    private void cancelarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarbtnMouseClicked

        Login L = new Login();
            L.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_cancelarbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CerrarBtn;
    private javax.swing.JLabel CerrarLbl;
    private javax.swing.JLabel FondoLlamaDevelopers;
    private javax.swing.JPanel MinimizarBtn;
    private javax.swing.JLabel MinimizarLbl;
    private javax.swing.JLabel TituloTxt1;
    private javax.swing.JLabel TituloTxt2;
    private javax.swing.JLabel TituloTxt3;
    private javax.swing.JButton cancelarbtn;
    private javax.swing.JLabel confirmarpasslbl;
    private javax.swing.JPasswordField confirmarpasstxt;
    private javax.swing.JLabel fechadenacimientolbl;
    private com.toedter.calendar.JDateChooser fechadenaciminetotxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passwordlbl;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JButton registrarbtn;
    private javax.swing.JLabel usuariolbl;
    private javax.swing.JTextField usuariotxt;
    // End of variables declaration//GEN-END:variables
}
